/* PARTENAIRES */
export const GET_PARTENAIRES = "GET_PARTENAIRES"
export const GET_PARTENAIRES_SUCCESS = "GET_PARTENAIRES_SUCCESS"
export const GET_PARTENAIRES_FAIL = "GET_PARTENAIRES_FAIL"

/* PARTENAIRES PROFILE */
export const GET_PARTENAIRE_PROFILE = "GET_PARTENAIRE_PROFILE"
export const GET_PARTENAIRE_PROFILE_SUCCESS = "GET_PARTENAIRE_PROFILE_SUCCESS"
export const GET_PARTENAIRE_PROFILE_FAIL = "GET_PARTENAIRE_PROFILE_FAIL"

/**
 * add PARTENAIRE
 */
export const ADD_NEW_PARTENAIRE = "ADD_NEW_PARTENAIRE"
export const ADD_PARTENAIRE_SUCCESS = "ADD_PARTENAIRE_SUCCESS"
export const ADD_PARTENAIRE_FAIL = "ADD_PARTENAIRE_FAIL"

/**
 * Edit PARTENAIRE
 */
export const UPDATE_PARTENAIRE = "UPDATE_PARTENAIRE"
export const UPDATE_PARTENAIRE_SUCCESS = "UPDATE_PARTENAIRE_SUCCESS"
export const UPDATE_PARTENAIRE_FAIL = "UPDATE_PARTENAIRE_FAIL"

/**
 * Delete PARTENAIRE
 */
export const DELETE_PARTENAIRE = "DELETE_PARTENAIRE"
export const DELETE_PARTENAIRE_SUCCESS = "DELETE_PARTENAIRE_SUCCESS"
export const DELETE_PARTENAIRE_FAIL = "DELETE_PARTENAIRE_FAIL"
